export const INITIAL_ADDRESS_STATE = {
  city: "",
  companyName: "",
  country: "",
  countryCode: "",
  firstName: "",
  lastName: "",
  phoneNumber: "",
  stateOrProvince: "",
  provinceCode: "",
  addressLineFirst: "",
  addressLineSecond: "",
  zipOrPostalCode: ""
};

export const STATE_OPTIONS = [
  { name: "Alabama", value: "Alabama" },
  { name: "Alaska", value: "Alaska" },
  { name: "Arizona", value: "Arizona" },
  { name: "Arkansas", value: "Arkansas" },
  { name: "California", value: "California" },
  { name: "Colorado", value: "Colorado" },
  { name: "Connecticut", value: "Connecticut" },
  { name: "Delaware", value: "Delaware" },
  { name: "Florida", value: "Florida" },
  { name: "Georgia", value: "Georgia" },
  { name: "Hawaii", value: "Hawaii" },
  { name: "Idaho", value: "Idaho" },
  { name: "Illinois", value: "Illinois" },
  { name: "Indiana", value: "Indiana" },
  { name: "Iowa", value: "Iowa" },
  { name: "Kansas", value: "Kansas" },
  { name: "Kentucky", value: "Kentucky" },
  { name: "Louisiana", value: "Louisiana" },
  { name: "Maine", value: "Maine" },
  { name: "Maryland", value: "Maryland" },
  { name: "Massachusetts", value: "Massachusetts" },
  { name: "Michigan", value: "Michigan" },
  { name: "Minnesota", value: "Minnesota" },
  { name: "Mississippi", value: "Mississippi" },
  { name: "Missouri", value: "Missouri" },
  { name: "Montana", value: "Montana" },
  { name: "Nebraska", value: "Nebraska" },
  { name: "Nevada", value: "Nevada" },
  { name: "New Hampshire", value: "Hampshire" },
  { name: "New Jersey", value: "Jersey" },
  { name: "New Mexico", value: "Mexico" },
  { name: "New York", value: "York" },
  { name: "North Carolina", value: "North Carolina" },
  { name: "North Dakota", value: "North Dakota" },
  { name: "Ohio", value: "Ohio" },
  { name: "Oklahoma", value: "Oklahoma" },
  { name: "Oregon", value: "Oregon" },
  { name: "Pennsylvania", value: "Pennsylvania" },
  { name: "Rhode Island", value: "Island" },
  { name: "South Carolina", value: "South Carolina" },
  { name: "South Dakota", value: "Dakota" },
  { name: "Tennessee", value: "Tennessee" },
  { name: "Texas", value: "Texas" },
  { name: "Utah", value: "Utah" },
  { name: "Vermont", value: "Vermont" },
  { name: "Virginia", value: "Virginia" },
  { name: "Washington", value: "Washington" },
  { name: "West Virginia", value: "West Virginia" },
  { name: "Wisconsin", value: "Wisconsin" },
  { name: "Wyoming", value: "Wyoming" },
  { name: "Moscow", value: "Moscow" },
  { name: "Saint Petersburg", value: "Saint Petersburg" }
];

export const CITY_OPTIONS = [
  { name: "Abilene", value: "Abilene" },
  { name: "Akron", value: "Akron" },
  { name: "Albuquerqu", value: "Albuquerqu" },
  { name: "Alexandria", value: "Alexandria" },
  { name: "Allentown", value: "Allentown" },
  { name: "Amarillo", value: "Amarillo" },
  { name: "Anaheim", value: "Anaheim" },
  { name: "Anchorage", value: "Anchorage" },
  { name: "Ann Arbor", value: "Ann Arbor" },
  { name: "Antioch", value: "Antioch" },
  { name: "Arlington", value: "Arlington" },
  { name: "Arvada", value: "Arvada" },
  { name: "Athens", value: "Athens" },
  { name: "Atlanta", value: "Atlanta" },
  { name: "Augusta", value: "Augusta" },
  { name: "Aurora", value: "Aurora" },
  { name: "Austin", value: "Austin" },
  { name: "Bakersfield", value: "Bakersfield" },
  { name: "Baltimore", value: "Baltimore" },
  { name: "Baton Rouge", value: "Baton Rouge" },
  { name: "Beaumont", value: "Beaumont" },
  { name: "Bellevue", value: "Bellevue" },
  { name: "Berkeley", value: "Berkeley" },
  { name: "Billings", value: "Billings" },
  { name: "Birmingham", value: "Birmingham" },
  { name: "Boise", value: "Boise" },
  { name: "Boston", value: "Boston" },
  { name: "Boulder", value: "Boulder" },
  { name: "Bridgeport", value: "Bridgeport" },
  { name: "Brownsville", value: "Brownsville" },
  { name: "Buffalo", value: "Buffalo" },
  { name: "Burbank", value: "Burbank" },
  { name: "Cambridge", value: "Cambridge" },
  { name: "Cape Cor", value: "Cape Cor" },
  { name: "Carrollton", value: "Carrollton" },
  { name: "Car", value: "Car" },
  { name: "Cedar Rapids", value: "Cedar Rapids" },
  { name: "Centennial", value: "Centennial" },
  { name: "Chandler", value: "Chandler" },
  { name: "Charlesto", value: "Charlesto" },
  { name: "Charlotte", value: "Charlotte" },
  { name: "Chattanooga", value: "Chattanooga" },
  { name: "Chesapeake", value: "Chesapeake" },
  { name: "Chicago", value: "Chicago" },
  { name: "Chula Vista", value: "Chula Vista" },
  { name: "Cincinnati", value: "Cincinnati" },
  { name: "Clarksville", value: "Clarksville" },
  { name: "Clearwater", value: "Clearwater" },
  { name: "Cleveland", value: "Cleveland" },
  { name: "Colorado Springs", value: "Colorado Springs" },
  { name: "Columbi", value: "Columbi" },
  { name: "Columbia", value: "Columbia" },
  { name: "Columbus", value: "Columbus" },
  { name: "Concord", value: "Concord" },
  { name: "Coral Springs", value: "Coral Springs" },
  { name: "Corona", value: "Corona" },
  { name: "Corpus Christi", value: "Corpus Christi" },
  { name: "Costa Mesa", value: "Costa Mesa" },
  { name: "Dallas", value: "Dallas" },
  { name: "Daly City", value: "Daly City" },
  { name: "Davenport", value: "Davenport" },
  { name: "Dayton", value: "Dayton" },
  { name: "Denton", value: "Denton" },
  { name: "Denver", value: "Denver" },
  { name: "Des Moines", value: "Des Moines" },
  { name: "Detroit", value: "Detroit" },
  { name: "Downey", value: "Downey" },
  { name: "Durha", value: "Durha" },
  { name: "El Monte", value: "El Monte" },
  { name: "El Paso", value: "El Paso" },
  { name: "Elgin", value: "Elgin" },
  { name: "Elizabet", value: "Elizabet" },
  { name: "Elk Grove", value: "Elk Grove" },
  { name: "Erie", value: "Erie" },
  { name: "Escondido", value: "Escondido" },
  { name: "Eugene", value: "Eugene" },
  { name: "Evansville", value: "Evansville" },
  { name: "Fairfield", value: "Fairfield" },
  { name: "Fayettevill", value: "Fayettevill" },
  { name: "Flint", value: "Flint" },
  { name: "Fontana", value: "Fontana" },
  { name: "Fort Collins", value: "Fort Collins" },
  { name: "Fort Lauderdale", value: "Fort Lauderdale" },
  { name: "Fort Wayne", value: "Fort Wayne" },
  { name: "Fort Worth", value: "Fort Worth" },
  { name: "Fremont", value: "Fremont" },
  { name: "Fresno", value: "Fresno" },
  { name: "Frisco", value: "Frisco" },
  { name: "Fullerton", value: "Fullerton" },
  { name: "Gainesville", value: "Gainesville" },
  { name: "Garden Grove", value: "Garden Grove" },
  { name: "Garland", value: "Garland" },
  { name: "Gilbert", value: "Gilbert" },
  { name: "Glendale", value: "Glendale" },
  { name: "Grand Prairie", value: "Grand Prairie" },
  { name: "Grand Rapids", value: "Grand Rapids" },
  { name: "Green Bay", value: "Green Bay" },
  { name: "Greensbor", value: "Greensbor" },
  { name: "Gresham", value: "Gresham" },
  { name: "Hampton", value: "Hampton" },
  { name: "Hartford", value: "Hartford" },
  { name: "Hayward", value: "Hayward" },
  { name: "Henderson", value: "Henderson" },
  { name: "Hialeah", value: "Hialeah" },
  { name: "High Point", value: "High Point" },
  { name: "Hollywood", value: "Hollywood" },
  { name: "Honolulu", value: "Honolulu" },
  { name: "Houston", value: "Houston" },
  { name: "Huntington Beach", value: "Huntington Beach" },
  { name: "Huntsville", value: "Huntsville" },
  { name: "Independence", value: "Independence" },
  { name: "Indianapolis", value: "Indianapolis" },
  { name: "Inglewood", value: "Inglewood" },
  { name: "Irvine", value: "Irvine" },
  { name: "Irving", value: "Irving" },
  { name: "Jackson", value: "Jackson" },
  { name: "Jacksonville", value: "Jacksonville" },
  { name: "Jersey City", value: "Jersey City" },
  { name: "Joliet", value: "Joliet" },
  { name: "Kansas", value: "Kansas" },
  { name: "Kansas City", value: "Kansas City" },
  { name: "Killeen", value: "Killeen" },
  { name: "Knoxville", value: "Knoxville" },
  { name: "Lafayette", value: "Lafayette" },
  { name: "Lakewood", value: "Lakewood" },
  { name: "Lancaster", value: "Lancaster" },
  { name: "Lansing", value: "Lansing" },
  { name: "Laredo", value: "Laredo" },
  { name: "Las Vegas", value: "Las Vegas" },
  { name: "Lewisville", value: "Lewisville" },
  { name: "Lexington", value: "Lexington" },
  { name: "Lincoln", value: "Lincoln" },
  { name: "Little Rock", value: "Little Rock" },
  { name: "Long Beach", value: "Long Beach" },
  { name: "Los Angeles", value: "Los Angeles" },
  { name: "Louisville", value: "Louisville" },
  { name: "Lowell", value: "Lowell" },
  { name: "Lubbock", value: "Lubbock" },
  { name: "Madison", value: "Madison" },
  { name: "Mancheste", value: "Mancheste" },
  { name: "McAllen", value: "McAllen" },
  { name: "McKinney", value: "McKinney" },
  { name: "Memphis", value: "Memphis" },
  { name: "Mesa", value: "Mesa" },
  { name: "Mesquite", value: "Mesquite" },
  { name: "Miami", value: "Miami" },
  { name: "Miami Gardens", value: "Miami Gardens" },
  { name: "Midland", value: "Midland" },
  { name: "Milwaukee", value: "Milwaukee" },
  { name: "Minneapolis", value: "Minneapolis" },
  { name: "Miramar", value: "Miramar" },
  { name: "Mobile", value: "Mobile" },
  { name: "Modesto", value: "Modesto" },
  { name: "Montgomery", value: "Montgomery" },
  { name: "Moreno Valley", value: "Moreno Valley" },
  { name: "Murfreesboro", value: "Murfreesboro" },
  { name: "Naperville", value: "Naperville" },
  { name: "Nashville", value: "Nashville" },
  { name: "New Haven", value: "New Haven" },
  { name: "New Orleans", value: "New Orleans" },
  { name: "New York", value: "New York" },
  { name: "Newark", value: "Newark" },
  { name: "Newport News", value: "Newport News" },
  { name: "Norfolk", value: "Norfolk" },
  { name: "Norman", value: "Norman" },
  { name: "North Las", value: "North Las" },
  { name: "Norwalk", value: "Norwalk" },
  { name: "Oakland", value: "Oakland" },
  { name: "Oceanside", value: "Oceanside" },
  { name: "Odessa", value: "Odessa" },
  { name: "Oklahoma City", value: "Oklahoma City" },
  { name: "Olathe", value: "Olathe" },
  { name: "Omaha", value: "Omaha" },
  { name: "Ontario", value: "Ontario" },
  { name: "Orange", value: "Orange" },
  { name: "Orlando", value: "Orlando" },
  { name: "Overland Park", value: "Overland Park" },
  { name: "Oxnard", value: "Oxnard" },
  { name: "Palm B", value: "Palm B" },
  { name: "Palmdale", value: "Palmdale" },
  { name: "Pasadena", value: "Pasadena" },
  { name: "Paterso", value: "Paterso" },
  { name: "Pembroke Pines", value: "Pembroke Pines" },
  { name: "Peoria", value: "Peoria" },
  { name: "Philadelphia", value: "Philadelphia" },
  { name: "Phoenix", value: "Phoenix" },
  { name: "Pittsburgh", value: "Pittsburgh" },
  { name: "Plano", value: "Plano" },
  { name: "Pomona", value: "Pomona" },
  { name: "Pompano Beach", value: "Pompano Beach" },
  { name: "Port St", value: "Port St" },
  { name: "Portland", value: "Portland" },
  { name: "Providenc", value: "Providenc" },
  { name: "Provo", value: "Provo" },
  { name: "Pueblo", value: "Pueblo" },
  { name: "Raleigh", value: "Raleigh" },
  { name: "Rancho Cucamonga", value: "Rancho Cucamonga" },
  { name: "Reno", value: "Reno" },
  { name: "Richardson", value: "Richardson" },
  { name: "Richmond", value: "Richmond" },
  { name: "Riverside", value: "Riverside" },
  { name: "Rocheste", value: "Rocheste" },
  { name: "Rochester", value: "Rochester" },
  { name: "Rockford", value: "Rockford" },
  { name: "Roseville", value: "Roseville" },
  { name: "Round Rock", value: "Round Rock" },
  { name: "Sacramento", value: "Sacramento" },
  { name: "Salem", value: "Salem" },
  { name: "Salinas", value: "Salinas" },
  { name: "Salt Lake", value: "Salt Lake" },
  { name: "San Antonio", value: "San Antonio" },
  { name: "San Bernardino", value: "San Bernardino" },
  { name: "San Buenaventura", value: "San Buenaventura" },
  { name: "San Diego", value: "San Diego" },
  { name: "San Francisco", value: "San Francisco" },
  { name: "San Jose", value: "San Jose" },
  { name: "Santa Ana", value: "Santa Ana" },
  { name: "Santa Clara", value: "Santa Clara" },
  { name: "Santa Clarita", value: "Santa Clarita" },
  { name: "Santa Rosa", value: "Santa Rosa" },
  { name: "Savannah", value: "Savannah" },
  { name: "Scottsdale", value: "Scottsdale" },
  { name: "Seattle", value: "Seattle" },
  { name: "Shreveport", value: "Shreveport" },
  { name: "Simi Valley", value: "Simi Valley" },
  { name: "Sioux Falls", value: "Sioux Falls" },
  { name: "South Bend", value: "South Bend" },
  { name: "Spokane", value: "Spokane" },
  { name: "Springfield", value: "Springfield" },
  { name: "St. Louis", value: "St. Louis" },
  { name: "St. Paul", value: "St. Paul" },
  { name: "St. Petersburg", value: "St. Petersburg" },
  { name: "Stamford", value: "Stamford" },
  { name: "Sterling Heights", value: "Sterling Heights" },
  { name: "Stockton", value: "Stockton" },
  { name: "Sunnyvale", value: "Sunnyvale" },
  { name: "Syracuse", value: "Syracuse" },
  { name: "Tacoma", value: "Tacoma" },
  { name: "Tallahassee", value: "Tallahassee" },
  { name: "Tampa", value: "Tampa" },
  { name: "Tempe", value: "Tempe" },
  { name: "Thornton", value: "Thornton" },
  { name: "Thousand Oaks", value: "Thousand Oaks" },
  { name: "Toledo", value: "Toledo" },
  { name: "Topeka", value: "Topeka" },
  { name: "Torrance", value: "Torrance" },
  { name: "Tucson", value: "Tucson" },
  { name: "Tulsa", value: "Tulsa" },
  { name: "Vallejo", value: "Vallejo" },
  { name: "Vancouver", value: "Vancouver" },
  { name: "Victorville", value: "Victorville" },
  { name: "Virginia Beach", value: "Virginia Beach" },
  { name: "Visalia", value: "Visalia" },
  { name: "Waco", value: "Waco" },
  { name: "Warren", value: "Warren" },
  { name: "Washingto", value: "Washingto" },
  { name: "Waterbury", value: "Waterbury" },
  { name: "West Covina", value: "West Covina" },
  { name: "West Jordan", value: "West Jordan" },
  { name: "West Valley", value: "West Valley" },
  { name: "Westminster", value: "Westminster" },
  { name: "Wichita", value: "Wichita" },
  { name: "Wichita Falls", value: "Wichita Falls" },
  { name: "Wilmingto", value: "Wilmingto" },
  { name: "Winston-Sale", value: "Winston-Sale" },
  { name: "Worcester", value: "Worcester" },
  { name: "Yonker", value: "Yonker" },
  { name: "Moscow", value: "Moscow" },
  { name: "Saint Petersburg", value: "Saint Petersburg" }
];

export const COUNTRY_OPTIONS = [
  { name: "Abkhazia", value: "Abkhazia" },
  { name: "Australia", value: "Australia" },
  { name: "Austria", value: "Austria" },
  { name: "Azerbaijan", value: "Azerbaijan" },
  { name: "Aland Islands", value: "Aland Islands" },
  { name: "Albania", value: "Albania" },
  { name: "Algeria", value: "Algeria" },
  { name: "Anguilla", value: "Anguilla" },
  { name: "Angola", value: "Angola" },
  { name: "Andorra", value: "Andorra" },
  { name: "Argentina", value: "Argentina" },
  { name: "Armenia", value: "Armenia" },
  { name: "Aruba", value: "Aruba" },
  { name: "Afghanistan", value: "Afghanistan" },
  { name: "Bahamas", value: "Bahamas" },
  { name: "Bangladesh", value: "Bangladesh" },
  { name: "Barbados", value: "Barbados" },
  { name: "Bahrain", value: "Bahrain" },
  { name: "Belarus", value: "Belarus" },
  { name: "Belize", value: "Belize" },
  { name: "Belgium", value: "Belgium" },
  { name: "Benin", value: "Benin" },
  { name: "Bulgaria", value: "Bulgaria" },
  { name: "Bolivia", value: "Bolivia" },
  { name: "Bosnia & Herzegov", value: "Bosnia & Herzegov" },
  { name: "Botswana", value: "Botswana" },
  { name: "Brazil", value: "Brazil" },
  { name: "Brunei Darussalam", value: "Brunei Darussalam" },
  { name: "Burundi", value: "Burundi" },
  { name: "Bhutan", value: "Bhutan" },
  { name: "Vatican City", value: "Vatican City" },
  { name: "United Kingdom", value: "United Kingdom" },
  { name: "Hungary", value: "Hungary" },
  { name: "Venezuela", value: "Venezuela" },
  { name: "Timor, E", value: "Timor, E" },
  { name: "Viet Nam", value: "Viet Nam" },
  { name: "Gabon", value: "Gabon" },
  { name: "Haiti", value: "Haiti" },
  { name: "Gambia", value: "Gambia" },
  { name: "Ghana", value: "Ghana" },
  { name: "Guadeloupe", value: "Guadeloupe" },
  { name: "Guatemala", value: "Guatemala" },
  { name: "Guinea", value: "Guinea" },
  { name: "Guinea-Bissau", value: "Guinea-Bissau" },
  { name: "Germany", value: "Germany" },
  { name: "Gibraltar", value: "Gibraltar" },
  { name: "Hong Kong", value: "Hong Kong" },
  { name: "Honduras", value: "Honduras" },
  { name: "Grenada", value: "Grenada" },
  { name: "Greenland", value: "Greenland" },
  { name: "Greece", value: "Greece" },
  { name: "Georgia", value: "Georgia" },
  { name: "Guam", value: "Guam" },
  { name: "Denmark", value: "Denmark" },
  { name: "Dominica", value: "Dominica" },
  { name: "Dominican Republic", value: "Dominican Republic" },
  { name: "Egypt", value: "Egypt" },
  { name: "Zambia", value: "Zambia" },
  { name: "Western Sahara", value: "Western Sahara" },
  { name: "Zimbabwe", value: "Zimbabwe" },
  { name: "Israel", value: "Israel" },
  { name: "India", value: "India" },
  { name: "Indonesia", value: "Indonesia" },
  { name: "Jordan", value: "Jordan" },
  { name: "Iraq", value: "Iraq" },
  { name: "Iran", value: "Iran" },
  { name: "Ireland", value: "Ireland" },
  { name: "Iceland", value: "Iceland" },
  { name: "Spain", value: "Spain" },
  { name: "Italy", value: "Italy" },
  { name: "Yemen", value: "Yemen" },
  { name: "Kazakhstan", value: "Kazakhstan" },
  { name: "Cambodia", value: "Cambodia" },
  { name: "Cameroon", value: "Cameroon" },
  { name: "Canada", value: "Canada" },
  { name: "Qatar", value: "Qatar" },
  { name: "Kenya", value: "Kenya" },
  { name: "Cyprus", value: "Cyprus" },
  { name: "Kyrgyzstan", value: "Kyrgyzstan" },
  { name: "Kiribati", value: "Kiribati" },
  { name: "China", value: "China" },
  { name: "Colombia", value: "Colombia" },
  { name: "Korea,", value: "Korea," },
  { name: "Korea", value: "Korea" },
  { name: "Costa Rica", value: "Costa Rica" },
  { name: "Cote d'Ivo", value: "Cote d'Ivo" },
  { name: "Cuba", value: "Cuba" },
  { name: "Kuwait", value: "Kuwait" },
  { name: "Lao P", value: "Lao P" },
  { name: "Latvia", value: "Latvia" },
  { name: "Lesotho", value: "Lesotho" },
  { name: "Liberia", value: "Liberia" },
  { name: "Lebanon", value: "Lebanon" },
  { name: "Libyan Arab Jamahir", value: "Libyan Arab Jamahir" },
  { name: "Lithuania", value: "Lithuania" },
  { name: "Liechtenstein", value: "Liechtenstein" },
  { name: "Luxembourg", value: "Luxembourg" },
  { name: "Mauritius", value: "Mauritius" },
  { name: "Mauritania", value: "Mauritania" },
  { name: "Madagascar", value: "Madagascar" },
  { name: "Macedonia", value: "Macedonia" },
  { name: "Malawi", value: "Malawi" },
  { name: "Malaysia", value: "Malaysia" },
  { name: "Mali", value: "Mali" },
  { name: "Maldives", value: "Maldives" },
  { name: "Malta", value: "Malta" },
  { name: "Morocco", value: "Morocco" },
  { name: "Mexico", value: "Mexico" },
  { name: "Mozambique", value: "Mozambique" },
  { name: "Moldova", value: "Moldova" },
  { name: "Monaco", value: "Monaco" },
  { name: "Mongolia", value: "Mongolia" },
  { name: "Namibia", value: "Namibia" },
  { name: "Nepal", value: "Nepal" },
  { name: "Niger", value: "Niger" },
  { name: "Nigeria", value: "Nigeria" },
  { name: "Netherlands", value: "Netherlands" },
  { name: "Nicaragua", value: "Nicaragua" },
  { name: "New Zealand", value: "New Zealand" },
  { name: "Norway", value: "Norway" },
  { name: "United Arab Emira", value: "United Arab Emira" },
  { name: "Oman", value: "Oman" },
  { name: "Pakistan", value: "Pakistan" },
  { name: "Panama", value: "Panama" },
  { name: "Paraguay", value: "Paraguay" },
  { name: "Peru", value: "Peru" },
  { name: "Poland", value: "Poland" },
  { name: "Portugal", value: "Portugal" },
  { name: "Russia", value: "Russia" },
  { name: "Romania", value: "Romania" },
  { name: "San Marino", value: "San Marino" },
  { name: "Saudi Arabia", value: "Saudi Arabia" },
  { name: "Senegal", value: "Senegal" },
  { name: "Serbia", value: "Serbia" },
  { name: "Singapore", value: "Singapore" },
  { name: "Syrian Arab Repub", value: "Syrian Arab Repub" },
  { name: "Slovakia", value: "Slovakia" },
  { name: "Slovenia", value: "Slovenia" },
  { name: "Somalia", value: "Somalia" },
  { name: "Sudan", value: "Sudan" },
  { name: "USA", value: "USA" },
  { name: "Tajikistan", value: "Tajikistan" },
  { name: "Thailand", value: "Thailand" },
  { name: "Tanzania", value: "Tanzania" },
  { name: "Togo", value: "Togo" },
  { name: "Tunisia", value: "Tunisia" },
  { name: "Turkmenistan", value: "Turkmenistan" },
  { name: "Turkey", value: "Turkey" },
  { name: "Uganda", value: "Uganda" },
  { name: "Uzbekistan", value: "Uzbekistan" },
  { name: "Ukraine", value: "Ukraine" },
  { name: "Uruguay", value: "Uruguay" },
  { name: "Micronesia", value: "Micronesia" },
  { name: "Fiji", value: "Fiji" },
  { name: "Philippines", value: "Philippines" },
  { name: "Finland", value: "Finland" },
  { name: "France", value: "France" },
  { name: "Croatia", value: "Croatia" },
  { name: "Chad", value: "Chad" },
  { name: "Montenegro", value: "Montenegro" },
  { name: "Czech Republic", value: "Czech Republic" },
  { name: "Chile", value: "Chile" },
  { name: "Switzerland", value: "Switzerland" },
  { name: "Sweden", value: "Sweden" },
  { name: "Sri Lanka", value: "Sri Lanka" },
  { name: "Ecuador", value: "Ecuador" },
  { name: "Eritrea", value: "Eritrea" },
  { name: "Estonia", value: "Estonia" },
  { name: "Ethiopia", value: "Ethiopia" },
  { name: "South Africa", value: "South Africa" },
  { name: "Jamaica", value: "Jamaica" },
  { name: "Japan", value: "Japan" }
];
